// <auto-generated />
using System;
using BlazorCRUD.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUD.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220219164347_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorCRUD.Shared.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearlyBudget")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "Cracow",
                            Name = "IT",
                            YearlyBudget = 10000
                        },
                        new
                        {
                            ID = 2,
                            Location = "Warsaw",
                            Name = "Finance",
                            YearlyBudget = 5000
                        },
                        new
                        {
                            ID = 3,
                            Location = "Cracow",
                            Name = "RD",
                            YearlyBudget = 8000
                        },
                        new
                        {
                            ID = 4,
                            Location = "Warsaw",
                            Name = "Management",
                            YearlyBudget = 7000
                        });
                });

            modelBuilder.Entity("BlazorCRUD.Shared.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<byte>("DepartmentID")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DepartmentID1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID1");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = (byte)1,
                            Name = "Forrest",
                            Salary = 5000,
                            Surname = "Gump"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = (byte)2,
                            Name = "Johnny",
                            Salary = 5000,
                            Surname = "Bravo"
                        });
                });

            modelBuilder.Entity("BlazorCRUD.Shared.Employee", b =>
                {
                    b.HasOne("BlazorCRUD.Shared.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID1");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
